
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # Job 1: Build and test the Docker image
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker Buildx (for building images)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t hello-world-app .

    # Step 4: Test the Docker image
    - name: Test Docker image
      run: |
        docker run hello-world-app

  # Job 2: Push the Docker image to DockerHub
  push-to-dockerhub:
    needs: build-and-test # Ensure this job runs after "build-and-test"
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and push Docker image to DockerHub
    - name: Push Docker image
      run: |
        docker build -t ${DOCKER_USERNAME}/hello-world-app:latest .
        docker push ${DOCKER_USERNAME}/hello-world-app:latest

  # Job 3: Deploy the Docker image to a remote server
  deploy:
    needs: push-to-dockerhub # Ensure this job runs after "push-to-dockerhub"
    runs-on: ubuntu-latest

    steps:
    # Step 1: Deploy to the remote server
    - name: Deploy to remote server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no user@your-server-ip "
          docker pull ${DOCKER_USERNAME}/hello-world-app:latest &&
          docker stop hello-container || true &&
          docker rm hello-container || true &&
          docker run -d --name hello-container ${DOCKER_USERNAME}/hello-world-app:latest
        "
