name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout kodu źródłowego
    - name: Checkout Code
      uses: actions/checkout@v3

    # Instalacja Dockera
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Budowanie obrazu Dockera
    - name: Build Docker Image
      run: |
        docker build -t hello-world-app .

    # Testowanie aplikacji
    - name: Test Application
      run: |
        docker run hello-world-app

    # Push obrazu Dockera do DockerHub
    - name: Push Docker Image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USER}" --password-stdin
        docker tag hello-world-app ${DOCKER_USER}/hello-world-app:latest
        docker push ${DOCKER_USER}/hello-world-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ssh -i ~/.ssh/id_rsa user@server "
          docker pull ${DOCKER_USER}/hello-world-app:latest &&
          docker stop hello-container || true &&
          docker rm hello-container || true &&
          docker run -d --name hello-container ${DOCKER_USER}/hello-world-app:latest
        "
