
name: Build and Run Hello World in Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Build and run the Docker container
      - name: Build Docker image
        run: docker build -t hello-world-image .

      - name: Run Docker container
        run: docker run hello-world-image
